language: java
jdk:
- oraclejdk9
addons:
  sonarcloud:
    organization: sonarqubegeekshubs
script:
- mvn clean verify sonar:sonar -Pcoverage
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
notifications:
  email: false

